// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package state

import ()

type Book struct {
	ID       int64
	Complete int64
}

type Bookmembership struct {
	Bookid  int64
	Trackid int64
}

type Track struct {
	ID         int64
	Author     string
	Booktitle  string
	Diskindex  int64
	Trackindex int64
	Year       int64
	Filename   string
	Trackname  string
}
